---
efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - small
  - file
initialPartitioningChoice: erase
initialSwapChoice: small
drawNestedPartitions: true
defaultFileSystemType: "btrfs"
availableFileSystemTypes:
  - "btrfs"
  - "ext4"
  - "xfs"
