---
defaultGroups:
  - users
  - wheel
  - network
  - video
  - audio
  - storage
  - input
  - power

doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
userShell: /bin/bash

passwordRequirements:
  minLength: 1
