---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
  requiredStorage: 15
  requiredRam: 2.0
  checkHasInternet: false
  check:
    - storage
    - ram
    - root
  required:
    - storage
    - root
