---
# Nebula Linux — Calamares installer configuration.
# Installs by copying the live squashfs, then cleans live-only bits.
modules-search: [ local ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - shellprocess
      - initcpiocfg
      - initcpio
      - grubcfg
      - bootloader
      - umount
  - show:
      - finished

branding: nebula
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
